### ISSUE TITLE
visual studio code extension only installable from proprietary vscode

### ISSUE THREAD

**Issue by MangoIV** [polarity-lang/vscode#6]
VSCode's ToS disallow installing extensions from their proprietary marketplace. That makes it such that users of [vscodium](https://github.com/VSCodium/vscodium) and other open vscode compatible editors do not have access to the polarity extension. 
[Open VSX](https://open-vsx.org/) is a registry that can be used by both proprietary and open distributions of the vscode editor. 

Since the closed distribution of vscode [does not configure the open-vsx registry as a standard registry](https://github.com/eclipse/openvsx/wiki/Using-Open-VSX-in-VS-Code), it is probably not a good idea to switch to only open-vsx because that requires additional setup for users using the closed distribution. 

I would still find it nice if the polarity extension would also be published to open-vsx.

**Comment by MangoIV** [comment]
https://github.com/marketplace/actions/publish-vs-code-extension

There seems to be this which can do both

**Comment by MangoIV** [comment]
Ah - curious, I didn’t know of this repo and was manically searching for the vscode extension :P

**Comment by BinderDavid** [comment]
Applied for verified status here: https://github.com/EclipseFdn/open-vsx.org/issues/3167
